apiVersion: v1
kind: ReplicationController
metadata:
  name: host-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      containers:
      - name: host-nginx
        image: registry:5000/nginx:1.12
        ports:
        - containerPort: 80
