apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        #image: harbor-001.jimmysong.io/library/heapster-amd64:v1.3.0-beta.1
        image: registry:5000/heapster-amd64:v1.5.2
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes:http://192.168.44.142:8080?inClusterConfig=false
        - --sink=influxdb:http://monitoring-influxdb:8086
