apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tf-dsf-train
  name: tf-cluster-config
data:
  ps: "ps0.tf-dsf-train.svc.cluster.local:2222"
  worker: "worker0.tf-dsf-train.svc.cluster.local:2222,worker1.tf-dsf-train.svc.cluster.local:2222"
