apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: nginx
spec:
  type: NodePort
  externalIPs:
  - 192.168.44.146
  ports:
  - port: 80
    protocol: TCP
    name: http
    nodePort: 30000
  selector:
    app: nginx
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry:5000/nginx:1.12
        ports:
        - containerPort: 80
        volumeMounts:     
        - name: config-nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config-nginx
        configMap:
          name: nginx-conf
