apiVersion: v1
kind: ReplicationController
metadata:
 name: mysql-slave
 labels:
  name: mysql-slave
spec:
  replicas: 1
  selector:
   name: mysql-slave
  template:
   metadata:
    labels:
     name: mysql-slave
   spec:
    nodeSelector:
      mysql: slave
    containers:
    - name: mysql-slave
      image: registry:5000/mysql-slave:5.7
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-slave-data
        - name: mysql-slave-config
          mountPath: /etc/mysql/mysql.conf.d/mysqld.cnf
          subPath: mysqld.cnf
      ports:
      - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "12345678"
      - name: MYSQL_REPLICATION_USER
        value: "repl"
      - name: MYSQL_REPLICAITON_PASSWORD
        value: "12345678"
    volumes:
     - name: mysql-slave-data
       persistentVolumeClaim:
        claimName: pv-nfs-mysql-slave
     - name: mysql-slave-config
       configMap:
        name: mysql-slave-config
