apiVersion: v1
kind: ReplicationController
metadata:
 name: mysql-master
 labels:
  name: mysql-master
spec:
  replicas: 1
  selector:
   name: mysql-master
  template:
   metadata:
    labels:
     name: mysql-master
   spec:
    containers:
    - name: mysql-master
      image: registry:5000/mysql-master:5.7
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-master-data
        - name: mysql-config
          mountPath: /etc/mysql/mysql.conf.d/mysqld.cnf
          subPath: mysqld.cnf
      ports:
      - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "12345678"
      - name: MYSQL_REPLICATION_USER
        value: "repl"
      - name: MYSQL_REPLICAITON_PASSWORD
        value: "12345678"
    volumes:
     - name: mysql-master-data
       persistentVolumeClaim:
        claimName: pv-nfs-mysql-master
     - name: mysql-config
       configMap:
        name: mysql-config
